#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "\nRunning eslint...\n"
yarn lint
echo "\nRunning prettier...\n"
yarn prettify
echo "\nRunning typescript compiler...\n"
npx tsc
echo "\nRunning tests...\n"
yarn test
